from pathlib import Path

GT_DIR = Path("data/agriverse/labels/test")

# Prediction labels generated by the existing error-analysis run.
PRED_DIR = Path(
    "runs/detect/runs/detect/error_analysis_raw/labels"
)

IOU_THRESHOLD = 0.50

# One known malformed annotation is excluded from quantitative analysis.
INVALID_FILE = "_home_iman_Documents_big_dataset_rgb_3531.txt"
INVALID_LINE = 0


def yolo_to_xyxy(xc, yc, w, h):
    return [
        xc - w / 2,
        yc - h / 2,
        xc + w / 2,
        yc + h / 2,
    ]


def iou(a, b):

    x1 = max(a[0], b[0])
    y1 = max(a[1], b[1])
    x2 = min(a[2], b[2])
    y2 = min(a[3], b[3])

    iw = max(0, x2 - x1)
    ih = max(0, y2 - y1)

    intersection = iw * ih

    area_a = (
        max(0, a[2] - a[0])
        * max(0, a[3] - a[1])
    )

    area_b = (
        max(0, b[2] - b[0])
        * max(0, b[3] - b[1])
    )

    union = area_a + area_b - intersection

    if union <= 0:
        return 0

    return intersection / union


def read_boxes(path, predictions=False):

    boxes = []

    if not path.exists():
        return boxes

    with open(path) as f:

        for line in f:

            parts = line.strip().split()

            if not parts:
                continue

            if len(parts) < 5:
                continue

            cls = int(parts[0])

            xc = float(parts[1])
            yc = float(parts[2])
            w = float(parts[3])
            h = float(parts[4])

            boxes.append({
                "class": cls,
                "box": yolo_to_xyxy(
                    xc, yc, w, h
                ),
                "w": w,
                "h": h,
                "area": w * h,
                "confidence":
                    float(parts[5])
                    if predictions and len(parts) >= 6
                    else None
            })

    return boxes


detected_areas = []
missed_areas = []

excluded_count = 0


for gt_file in sorted(GT_DIR.glob("*.txt")):

    pred_file = PRED_DIR / gt_file.name

    gt = read_boxes(gt_file)

    pred = read_boxes(
        pred_file,
        predictions=True
    )

    # -----------------------------------------------------
    # Select valid weed ground-truth boxes.
    #
    # Exclude ONLY:
    # _home_iman_Documents_big_dataset_rgb_3531.txt
    # line 0
    #
    # This is the known zero-width malformed annotation.
    # The original dataset file is NOT modified.
    # -----------------------------------------------------

    gt_weeds = []

    for i, x in enumerate(gt):

        if x["class"] != 1:
            continue

        if (
            gt_file.name == INVALID_FILE
            and i == INVALID_LINE
        ):
            excluded_count += 1
            continue

        gt_weeds.append(x)

    pred_weeds = [
        x for x in pred
        if x["class"] == 1
    ]

    # -----------------------------------------------------
    # Match predictions to GT weeds using IoU >= 0.50.
    # -----------------------------------------------------

    matches = []

    for pi, p in enumerate(pred_weeds):

        for gi, g in enumerate(gt_weeds):

            score = iou(
                p["box"],
                g["box"]
            )

            if score >= IOU_THRESHOLD:

                matches.append(
                    (score, pi, gi)
                )

    # Highest IoU matches first.
    matches.sort(
        reverse=True
    )

    matched_pred = set()
    matched_gt = set()

    for score, pi, gi in matches:

        if pi in matched_pred:
            continue

        if gi in matched_gt:
            continue

        matched_pred.add(pi)
        matched_gt.add(gi)

    # -----------------------------------------------------
    # Record GT weed areas.
    #
    # Matched GT weeds = detected weeds
    # Unmatched GT weeds = missed weeds
    # -----------------------------------------------------

    for gi, g in enumerate(gt_weeds):

        if gi in matched_gt:

            detected_areas.append(
                g["area"]
            )

        else:

            missed_areas.append(
                g["area"]
            )


# ---------------------------------------------------------
# Statistics
# ---------------------------------------------------------

def stats(values):

    values = sorted(values)

    n = len(values)

    if n == 0:
        return {}

    def percentile(p):

        index = int(
            p * (n - 1)
        )

        return values[index]

    return {
        "n": n,
        "min": values[0],
        "median": percentile(0.50),
        "q25": percentile(0.25),
        "q75": percentile(0.75),
        "max": values[-1],
        "mean": sum(values) / n,
    }


# ---------------------------------------------------------
# Output
# ---------------------------------------------------------

print()
print("=" * 60)
print("WEED OBJECT SIZE ANALYSIS")
print("=" * 60)

print()
print("Excluded malformed annotations:", excluded_count)

print()
print("Detected weeds:")

detected_stats = stats(detected_areas)

for k, v in detected_stats.items():

    if isinstance(v, float):

        print(
            f"{k:>8}: {v:.6f}"
        )

    else:

        print(
            f"{k:>8}: {v}"
        )


print()
print("Missed weeds:")

missed_stats = stats(missed_areas)

for k, v in missed_stats.items():

    if isinstance(v, float):

        print(
            f"{k:>8}: {v:.6f}"
        )

    else:

        print(
            f"{k:>8}: {v}"
        )


print()
print(
    "Total detected weeds:",
    len(detected_areas)
)

print(
    "Total missed weeds:",
    len(missed_areas)
)

print(
    "Total valid weed instances:",
    len(detected_areas) + len(missed_areas)
)

print()
print("=" * 60)
print("EXPECTED COUNTS")
print("=" * 60)

print("Expected detected: 495")
print("Expected missed:   114")
print("Expected valid:    609")
print()

